version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 190219743432.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t ghost-docker .
      - docker tag ghost-docker:latest 190219743432.dkr.ecr.ap-south-1.amazonaws.com/ghost-docker:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 190219743432.dkr.ecr.ap-south-1.amazonaws.com/ghost-docker:latest
